### ISSUE TITLE
upload problem

### ISSUE THREAD

**Issue by karthik2342323** [mohabmes/vsw#5]
video is not visible after uploading

**Comment by mohabmes** [comment]
Hi @karthik2342323

- Make sure you have created the uploads directory before actually uploading.
- Check for the uploads directory permission, is it writable or not.

├ Main vsw Directory 
│ └── media
│&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;├── thumbnail
│&nbsp; &nbsp; &nbsp; &nbsp;&nbsp;&nbsp;└── video
└── ...

**Comment by karthik2342323** [comment]
""" Please fill in the required fields: Title, Video and Thumbnail. """

 this message is occuring again and again even after selecting Title video and thumbnail

**Comment by mohabmes** [comment]
Ok, Use `git pull` first. and Make sure to handle the uploads directory issue and it should work just fine.
