### ISSUE TITLE
Special Key For encryption

### ISSUE THREAD

**Issue by Parth308** [mohabmes/vsw#6]
Pls tell me what is the security key which is used for encryption

**Comment by mohabmes** [comment]
Hi @Parth308, Would you please be more specific?

**Comment by Parth308** [comment]
Please tell how did you did the password encrypt

**Comment by Parth308** [comment]
There would a special key with whose help you encrypted the pass

**Comment by mohabmes** [comment]
There is no special key. as for password, [**md5**](https://www.php.net/manual/en/function.md5) hash is used.

**Comment by Parth308** [comment]
There is some error in the account panel it is not showing the videos
uploaded.just showing name and @ username

**Comment by mohabmes** [comment]
Kindly take a look at [this](https://github.com/mohabmes/vsw/issues/5).

**Comment by Parth308** [comment]
Bro  when I click on the name of channel nothing is showing this is my issue

**Comment by Parth308** [comment]
Thanks For telling
